### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by BUI-studies** [ohiienko-r/js-09-hw#1]
Коли перебиражш колекцію, використовуй методи масиву.
Ти завжди можеш зробити з HTMLCollection або NodeList масив та працювати з ним нормально.

Якшо такий підзід тобі пртивний, то є прикольна штука яка називаться `call` це метод який існує у кодної функції створенної в JS. Ця хжровіна дозволяє викликати одну функцію з іншим контекстом, тобто
```javascript
[].map.call(....)
```
викличе `map` з іншим контекстом, яким для неї може стати неприклад HTMLCollection

*task-03* - тебе ніхто не просив про eventListener-и. атата! все шо потрібно було це просто запитати промптом у юзера шо він собі думає за колір та профільтрувати по кольору. 

`e.textContent.includes(color) === false` - нема сенсу порівнювати з фолс, бо ти можеш поставити знак оклику перед самим інклюдс і працюватиме так само. далі, є моментик шо у тебе назві товару може бути колір і він не є кольором який внесений в систему, тому треба дивитись тільки на те шо написано після двокрапки.

`if (counter === listOfGoods.length) ` - простіше буде піти зворотнім шляхом та зробити так шоб каунтер залишався пустим якшо з таким кольором товарів нема. бо так воно звісно працює, але виглядає якось навиворіт.

**Comment by ohiienko-r** [comment]
0)На "ататата" за івент ліснер зійшлися на тому, що він був умові задачі;

1)Переписав логіку пошуку кольору в лайн айтемі. Тепер порівнюю введений колір тільки з тим, що після ":";

2)Переписав логіку каунтера: тепер він інкрементується якщо товар з таким кольором є в листі. Виніс логіку каунтера за межі колбеку;

![image](https://user-images.githubusercontent.com/109099364/235462036-ccc21dad-907d-4afa-9288-0e5a40d7b3b5.png)
